environment:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

install:
  - set PATH=C:\Ruby24-x64\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec fastlane test